[project]
name = "mcp-server-collection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.12.4",
    "requests>=2.31.0",
    "pytest>=7.0.0",
]
